services:
  moqui-search:
    image: opensearchproject/opensearch:2.19.1
    container_name: moqui-search
    restart: always
    ports:
      - "9200:9200"
    volumes:
      - ./opensearch/data:/usr/share/opensearch/data
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=OpenSearch1234!
      - discovery.type=single-node
      - network.host=_site_
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test: ["CMD-SHELL", "curl -k -u admin:OpenSearch1234! --silent --fail https://moqui-search:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 5